name: CodeCov
on: [ push, pull_request ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Generate Report
        run: |
          pip install poetry 
          poetry install
          poetry run coverage run -m pytest
          poetry run coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
